### ISSUE TITLE
Problem building spatialnetworks/shp-ruby with no internet connection from server (security reason)

### ISSUE THREAD

**Issue by spcrim** [fulcrumapp/shp-ruby#2]

**Comment by zhm** [comment]
What is the error?

**Comment by spcrim** [comment]
Hi
I enter the following commands to build  on a server that does not have internet connection  and get the following error.  Is there another way to build Ruby extension
mvn clean package
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/plugins/nexus-staging-maven-plugin/1.6.2/nexus-staging-maven-plugin-1.6.2.pom
[ERROR] The build could not read 1 project -> [Help 1]

**Comment by spcrim** [comment]
Sorry wrong extension

**Comment by spcrim** [comment]
I am running Hortonworks 2.3 Lunix VM that doesn’t have internet connection nor gem command. So where can I download gem for Lunix and will it be a problem if I don’t have internet connection.

**Comment by zhm** [comment]
It requires an internet connection. You can try setting up a 2nd VM of the same type _with_ an internet connection just to build/install it. Then you can copy the files over to the machine with no internet connection.
