### ISSUE TITLE
Support for Date format

### ISSUE THREAD

**Issue by nav16** [fulcrumapp/shp-ruby#3]
When creating a `.dbf`, the columns date format by default it takes as `C` with width = 8, instead the column format should be `D`. What am I missing?

```
dbf = SHP::DBF.create('data/data.dbf')
dbf.add_field('DOB', 0, 8, 0)

dbf.send("write_string_attribute", 0, 0, '20151225')
```

File data

| DOB,C,8 |
| --- |
| 20151225 |

Required

| DOB,D |
| --- |
| 20151225 |

**Comment by zhm** [comment]
This gem wraps Shapelib, which doesn't support creating DBF date fields.

The docs for the DBFAddField function can be found here:

http://shapelib.maptools.org/dbf_api.html
